# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0002_auto_20161206_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('POLIT', 'Politician'), ('PERIO', 'Journalist')], max_length=5, null=True, verbose_name='group'),
        ),
    ]
