# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0003_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(related_name='articles', to='bibloi.Theme'),
        ),
    ]
