# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0003_auto_20170114_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bibloi.Folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('POLIT', 'Politician'), ('PERIO', 'Journalist'), ('ANALI', 'Analyst')], max_length=5, null=True, verbose_name='group'),
        ),
    ]
