# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0004_auto_20170130_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bibloi.Folder', verbose_name='folder'),
        ),
    ]
