# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0005_article_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
