# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0007_auto_20170228_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
