# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0009_auto_20170302_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='name'),
        ),
    ]
