# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibloi', '0010_auto_20170302_0133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('name', 'parent')]),
        ),
    ]
